navigation:
  - title: "Home"
    url: "/index.html"
  - title: "Presentations"
    url: "/presentations"
  - title: "Publications"
    url: "/publications"
  - title: "Projects"
    url: "/projects"
  - title: "Vita"
    url: "/vita"

title: "Jared Howland"
author: "Jared Howland"
email: "jared_howland@byu.edu"
keywords: "'jared howland, vita, publications, presentations, projects'"
description: "'This is the personal website of Jared Howland, librarian at Brigham Young University - Harold B. Lee Library.'"
url: "http://www.jaredhowland.com"
ga-tracking-code: "UA-15180577-1"
ga-domain-name: "jaredhowland.com"
typekit-id: "bhp5uou"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

sass:
  style: :compressed

markdown: redcarpet
