# bundle exec jekyll serve --host localhost
navigation:
  - title: "Home"
    url: "/index.html"
  - title: "Presentations"
    url: "/presentations"
  - title: "Publications"
    url: "/publications"
  - title: "Projects"
    url: "/projects"
  - title: "Vitae"
    url: "/vita"

title: "Jared Howland"
author: "Jared L. Howland"
email: "jared_howland@byu.edu"
keywords: "'jared howland', vita, publications, presentations, projects"
description: "This is the personal website of Jared Howland, librarian at Brigham Young University - Harold B. Lee Library."
url: "https://www.jaredhowland.com"
ga-tracking-code: "UA-15180577-1"
ga-domain-name: "jaredhowland.com"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

sass:
  style: :compressed
